syntax = "proto3";

package http;

enum AccountRole {
    USER = 0;
    MOD = 1;
    DEV = 2;
    ADMIN = 3;
}

enum ResponseStatus {
    Ok = 200;
    InternalError = 500;

    InvalidBody = 400;
    NotAuthenticated = 401;
    VerificationFailure = 402;
    NotFound = 404;

    AccountExists = 450;
    AccountNotExists = 451;
    WrongPassword = 452;
}

message Profile {
    uint32 vp = 1;
    string username = 2;
    map<string, string> highest = 3;
    repeated string accessories = 4;
    AccountRole role = 5;
}

message RegisterRequest {
    string username = 1;
    string password = 2;
    string token = 3;
}

message LoginRequest { 
    string username = 1;
    string password = 2;
}

message LoginAndRegisterResponse {
    optional string token = 2;
    optional Profile profile = 3;
}

message ProfileResponse {
    optional Profile profile = 2;
}

message AuthResponse {
    optional Profile profile = 2;
}

message LogoutResponse {
    ResponseStatus status = 1;
}

message ServerElement {
    string icon = 1;
    string name = 2;
    string domain = 3;
    uint32 online = 4;
}

message ServersResponse {
    ResponseStatus status = 1;
    repeated ServerElement servers = 2;
}

message AdminModeServer {
    string id = 1;
    string icon = 2;
    string name = 3;
    string domain = 4;
}

message AdminModeServersResponse {
    repeated AdminModeServer servers = 1;
    uint32 online = 2;
    uint32 count = 3;
}

message AdminModeServerTokenResponse {
    string token = 1;
}

message AdminModeEditServerRequest {
    string id = 1;
    string name = 2;
    string icon = 3;
    optional string token = 4;
    string domain = 5;
}

message AdminModeAddServerRequest {
    string name = 2;
    string icon = 3;
    string token = 4;
    string domain = 5;
}

// Server HTTP

enum WorldEffect {
    RAIN = 1;
    RAINSTORM = 2;
    SNOW = 3;
    SNOWSTORM = 4;
    AUTUMN = 5;
}

message WorldProperties {
    message Background {
        string name = 1;
        uint32 alpha = 2;
    }

    string fillStyle = 1;
    string strokeStyle = 2;
    string areaFill = 3;
    optional uint32 areaAlpha = 4;
    repeated Background backgrounds = 5;
    optional WorldEffect effect = 6;
}

message AreaResponse {
    optional bool win = 1;
    optional uint32 vp = 2;
    optional string text = 3;
}

message WorldResponse {
    WorldProperties properties = 1;
    map<string, AreaResponse> areas = 2;
}

message WorldsResponse {
    map<string, WorldResponse> worlds = 1;
}