namespace AltverseServer;

enum Role : ubyte {
  User = 0,
  Mod,
  Dev
}

table Chat {
  id: uint32;
  content: string;
  author: string;
  role: Role;
  world: string;
}

table PackedEntity {
  type_id: ulong;
  x: float32;
  y: float32;
  radius: float32;
  harmless: bool;
  state: uint8;
  state_metadata: float32;
  alpha: float32;
}

table PackedPlayer {
  name: string;
  id: ulong;
  x: float32;
  y: float32;
  radius: float32;
  speed: float32;
  energy: float32;
  max_energy: float32;
  death_timer: float32;
  state: uint8;
  state_meta: float32;
  area: ulong;
  world: string;
  died: bool;
  hero: uint32;
}

table PartialEntity {
  x: float32 = null;
  y: float32 = null;
  radius: float32 = null;
  harmless: bool = null;
  state: uint8 = null;
  state_metadata: float32 = null;
  alpha: float32 = null;
}

table PartialPlayer {
  x: float32 = null;
  y: float32 = null;
  radius: float32 = null;
  speed: float32 = null;
  energy: float32  = null;
  max_energy: float32 = null;
  death_timer: float32 = null;
  state: ubyte = null;
  state_metadata: float32 = null;
  area: ulong = null;
  world: string;
  died: bool = null;
}

table PackedEntityMap {
  key: ulong;
  value: PackedEntity;
}

table PackedPlayerMap {
  key: uint;
  value: PackedPlayer;
}

table PackedArea {
  w: float32;
  h: float32;
  area: uint32;
  world: string;
  entities: [PackedEntityMap];
}

table Players {
  players: [PackedPlayerMap];
}

table Entities {
   entities: [PackedEntityMap];
}

table ClosePlayer {
  id: ulong;
}

table CloseEntities {
  ids: [ulong];
}

table PartialEntityMap {
  key: ulong;
  value: PartialEntity;
}

table PartialPlayerMap {
  key: ulong;
  value: PartialPlayer;
}

table UpdateEntities {
  items: [PartialEntityMap];
}

table UpdatePlayers {
  items: [PartialPlayerMap];
}

union PackageKind {
  new_player: PackedPlayer,
  close_player: ClosePlayer,
  players: Players,
  new_entities: Entities,
  close_entities: CloseEntities,
  area_init: PackedArea,
  myself: PackedPlayer,
  update_entities: UpdateEntities,
  update_players: UpdatePlayers,
  chat: Chat
}

table Package {
  kind: PackageKind;
}

table Packages {
  items: [Package];
}